spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goodsending
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jwt:
    secret: ${JWT_SECRET}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  mail:
    host: smtp.naver.com
    port: 465
    username: ${YOUR_NAVER_EMAIL}
    password: ${YOUR_NAVER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
  data:
    redis:
      host: localhost
      port: 6379
cloud:
  aws:
    credentials:
      access-key: ${IAM_ACCESS_KEY}
      secret-key: ${IAM_SECRET_KEY}
    region:
      static: ${S3_BUCKET_REGION}
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET_NAME}