spring:
  datasource:
    url: jdbc:h2:mem:~/goodsending
    driver-class-name: org.h2.Driver
    username: goods
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  mail:
    username: example
  data:
    redis:
      port: 6379
