spring:
  datasource:
    url: jdbc:h2:mem:~/goodsending
    driver-class-name: org.h2.Driver
    username: goods
    password:
  jwt:
    secret: ${JWT_SECRET}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
cloud:
  aws:
    credentials:
      access-key: ${IAM_ACCESS_KEY}
      secret-key: ${IAM_SECRET_KEY}
    region:
      static: ${S3_BUCKET_REGION}
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET_NAME}
