spring:
  profiles:
    default: local

  datasource:
    url: jdbc:mysql://localhost:3306/goodsending
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
---
spring:
  jwt:
    secret: ${JWT_SECRET}
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
---
spring:
  config:
    activate:
      on-profile: test # 테스트용 프로파일

  datasource:
    url: jdbc:h2:mem:~/goodsending
    driver-class-name: org.h2.Driver
    username: goods
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
